//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningCenter.ProductDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCart
    {
        public int CartId { get; set; }
        public int UserId { get; set; }
        public int ClassId { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
    
        public virtual ClassMaster ClassMaster { get; set; }
        public virtual User User { get; set; }
    }
}
